# configs/model/bert4rec.yaml
name: bert4rec
model_kwargs:
  hidden_dim: 64
  num_heads: 2
  num_layers: 2
  dropout: 0.2
train_kwargs:
  batch_size: 256
  epochs: 100
  lr: 1e-3
  weight_decay: 1e-4
  beta2: 0.98
  max_len: 50
  gradient_clip: 5.0
  early_stop_patience: 20
  early_stop_min_delta: 1e-4
  mask_ratio: 0.2
  warmup_steps: 0
  dupe_factor: 10
  prop_sliding_window: 0.1
  force_last_item_mask: true
  confidence_alpha: 0.0
